### ISSUE TITLE
Mise à jour des montants

### ISSUE THREAD

**Issue by ppezziardi** [sgmap/paie-carto#1]
lorsqu'un montant/combo est mis à jour sur le formulaire, les infos sur la carte sont mises à jour, ainsi que les montants sur le formulaire = "Cela coûtera 1561,69 € par mois à mon entreprise.
Mon salarié.e touchera 1124,81 € par mois et sera imposable à hauteur de 1166,00 €."

**Comment by blackrez** [comment]
Les montants sont mis à jour au survol des différentes zones.
