### ISSUE TITLE
Mettre à jour le simulateur d'embauche

### ISSUE THREAD

**Issue by MattiSG** [sgmap/paie-carto#11]
Le simulateur nouveau est arrivé !  ;)

Pour faciliter les mises à jour et utiliser une API plus fiable, passer à la nouvelle inclusion :

``` html
<script src="https://raw.githubusercontent.com/sgmap/cout-embauche/gh-pages/dist/cout-embauche-widget.js"></script>
```

Il faudra probablement remplacer le parsing de `old_sal` depuis le HTML par `getLastResults()`, ce qui devrait pas mal simplifier le code  ;)

[Détails](https://github.com/sgmap/cout-embauche/).

**Comment by MattiSG** [comment]
@blackrez J'ai corrigé les [deux](https://github.com/sgmap/cout-embauche/commit/1d446feb6868807813438cc8b1e257bafd682a35) [points](https://github.com/sgmap/cout-embauche/commit/b31bf2791619afbef2fa353bbd1c35525ea84f84) qu'on avait évoqués, dis-moi ce que ça donne  :)

**Comment by blackrez** [comment]
Malheureusement, ça ne change pas pour le salaire : https://gist.github.com/blackrez/fbc28abd1faacf96a5df.

**Comment by MattiSG** [comment]
Es-tu bien sûr d'utiliser l'URL `https://rawgit.com/sgmap/cout-embauche/gh-pages/dist/cout-embauche-widget.js` et pas une qui aurait mis en cache la version précédente… ?

**Comment by blackrez** [comment]
Bien vu, l'URL était https://cdn.rawgit.com/sgmap/cout-embauche/gh-pages/dist/cout-embauche-widget.js. Ça fonctionne.

**Comment by MattiSG** [comment]
:dancer:

**Comment by MattiSG** [comment]
Tu notifieras quand ce sera déployé ?  :)

**Comment by blackrez** [comment]
Bien sûr, je répare la css et 2-3 bricoles avant de passer ça en production.
