### ISSUE TITLE
support des ZRR

### ISSUE THREAD

**Issue by ppezziardi** [sgmap/paie-carto#3]

**Comment by blackrez** [comment]
Les ZRR ont été ajouté sur l'APICarto  : https://github.com/sgmap/apicarto-zoneville/commit/38ca0800a02e79ac027c87d90084fba010c24790

L'intégration est faite. Il reste un bug de style.

**Comment by blackrez** [comment]
C'est disponible : http://apicarto.coremaps.com/paie-carto/#
