### ISSUE TITLE
support des ZRD

### ISSUE THREAD

**Issue by ppezziardi** [sgmap/paie-carto#4]

**Comment by blackrez** [comment]
À ajouter dans APICarto-zoneville : 

http://www.legifrance.gouv.fr/affichTexte.do;jsessionid=?cidTexte=JORFTEXT000021042550&dateTexte&=categorieLien=id

Il faut parser l’arrêté pour en récupérer les communes concernées.

**Comment by blackrez** [comment]
![zonefrance](https://cloud.githubusercontent.com/assets/798369/7615655/522185aa-f99f-11e4-9b1f-2904649aeffb.png)

C'est dans les tuyaux, un peu d'interactivité et on sera bon.

**Comment by blackrez** [comment]
Les BER/ZRD/ZRR ont été ajoutés, le style est à revoir.
