### ISSUE TITLE
support des BER

### ISSUE THREAD

**Issue by ppezziardi** [sgmap/paie-carto#5]

**Comment by blackrez** [comment]
Dispositif créé par la loi de finances rectificative de 2006 qui ne concerne que deux régions : Champagne-Ardenne (zone d'emploi de la Vallée de la Meuse) et Midi-Pyrénées (zone d'emploi de Lavelanet).
http://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000465967

Il faut récupérer les code INSEE des communes concernées.

Pour la vallée de la Meuse : http://www.ardennes.cci.fr/pdf/zone-franche/communes-zonefranche.pdf

Aucune information pour Lavelanet.

**Comment by blackrez** [comment]
Nous avons reçu le fichier csv.

**Comment by blackrez** [comment]
https://github.com/sgmap/apicarto-zoneville/issues/1

**Comment by blackrez** [comment]
C'est lié au #4
